import React from "react";
import type { Metadata } from "next";
import "./globals.css";

// eslint-disable-next-line camelcase
import { Host_Grotesk } from "next/font/google";
import { ThemeProvider } from "@/context/ThemeProvider";

const hostGrotesk = Host_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-host-grotesk",
  preload: false,
});

export const metadata: Metadata = {
  title: "Vanni Looks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${hostGrotesk.variable} antialiased`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
